services:
  # --- BD/IA ---
  db:
    image: pgvector/pgvector:pg17
    container_name: my_postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documind

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_container
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: /bin/sh
    command: -c "/bin/ollama serve & sleep 5 && ollama pull phi3 && ollama pull nomic-embed-text && wait"

  # --- BACKEND ---
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: documind-backend:latest
    container_name: documind_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/documind
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_AI_OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - db
      - ollama

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: documind-frontend:latest
    environment:
      - BACKEND_URL=http://backend:8080
    container_name: documind_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
  ollama_data: