apiVersion: v1
kind: ConfigMap
metadata:
  name: documind-config
data:
  datasource-url: jdbc:postgresql://db-service:5432/documind
  ollama-base-url: http://ollama-service:11434
  backend-url: http://backend-service:8080